// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"he_IL": &dictionary{index: he_ILIndex, data: he_ILData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"The set local is %s\n": 0,
}

var en_GBIndex = []uint32{ // 2 elements
	0x00000000, 0x0000001c,
} // Size: 32 bytes

const en_GBData string = "\x04\x00\x01\n\x17\x02The set local is %[1]s"

var en_USIndex = []uint32{ // 2 elements
	0x00000000, 0x0000001c,
} // Size: 32 bytes

const en_USData string = "\x04\x00\x01\n\x17\x02The set local is %[1]s"

var he_ILIndex = []uint32{ // 2 elements
	0x00000000, 0x00000024,
} // Size: 32 bytes

const he_ILData string = "\x04\x00\x01\n\x1f\x02שפת הממשק היא %[1]s"

// Total table size 188 bytes (0KiB); checksum: CE54A1CC
