name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.17.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.5.0
      id: setup-go-faster
      with:
        go-version: ${{ matrix.go-version }}
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
      if: ${{ runner.os == 'Linux' }}
      
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: GetFyne
      run: |
         go install fyne.io/fyne/v2@latest
         go install fyne.io/fyne/v2/cmd/fyne@latest
         fyne install
    
    - name: TestBuild
      run: go build -ldflags -H=windowsgui .\HelloWorld.go
    
    - name: FyneBuild
      run: |
          pwd
          dir
          fyne package -icon ..\Resources\RSLicon.png

    
